# Generated by Django 3.1.7 on 2021-04-08 18:44

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quarantine',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('first_test', models.CharField(default='untested', max_length=20)),
                ('second_test', models.CharField(default='untested', max_length=20)),
                ('status', models.CharField(default='outOfKorea', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Quarantine',
            },
        ),
    ]
