# Generated by Django 3.1.7 on 2021-04-07 02:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quarantine',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstTest', models.CharField(default='untested', max_length=20)),
                ('secondTest', models.CharField(default='untested', max_length=20)),
                ('status', models.CharField(default='outOfKorea', max_length=20)),
            ],
            options={
                'db_table': 'Quarantine',
            },
        ),
    ]
