# Generated by Django 3.1.7 on 2021-04-07 02:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('country', '0001_initial'),
        ('quarantine', '0001_initial'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('firstName', models.CharField(blank=True, max_length=50, null=True)),
                ('lastName', models.CharField(blank=True, max_length=50, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=12, null=True)),
                ('kakaoID', models.CharField(blank=True, max_length=50, null=True)),
                ('currentLocation', models.TextField(blank=True, null=True)),
                ('isVerified', models.BooleanField(default=False)),
                ('arrivalDateTime', models.DateTimeField(auto_now_add=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address')),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='country.country')),
                ('quarantine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quarantine.quarantine')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_university', to='university.university')),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
