# Generated by Django 3.1.7 on 2021-04-08 18:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('english_address', models.TextField()),
                ('address_detail', models.TextField()),
                ('zipcode', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lang', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Address',
            },
        ),
    ]
